language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis-macos.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux.sh; fi